/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bwsoft_athena_jni_NativeUtil */

#ifndef _Included_com_bwsoft_athena_jni_NativeUtil
#define _Included_com_bwsoft_athena_jni_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bwsoft_athena_jni_NativeUtil
 * Method:    getLXRandom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bwsoft_athena_jni_NativeUtil_getLXRandom
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
