/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bwsoft_athena_jni_ObservableOfNativeByteArray */

#ifndef _Included_com_bwsoft_athena_jni_ObservableOfNativeByteArray
#define _Included_com_bwsoft_athena_jni_ObservableOfNativeByteArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bwsoft_athena_jni_ObservableOfNativeByteArray
 * Method:    startNativeObservable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bwsoft_athena_jni_ObservableOfNativeByteArray_startNativeObservable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
