/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bwsoft_athena_jni_ThreadDemo */

#ifndef _Included_com_bwsoft_athena_jni_ThreadDemo
#define _Included_com_bwsoft_athena_jni_ThreadDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bwsoft_athena_jni_ThreadDemo
 * Method:    pinThreadNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_bwsoft_athena_jni_ThreadDemo_pinThreadNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
