//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 06:50:24 PM CDT 
//


package com.bwsoft.athena.jaxb.pm;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for participantMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="participantMappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MappingEntry" type="{}MappingEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="creation-date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="fromExchange" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="RemoteExch" />
 *       &lt;attribute name="toExchange" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="LocalExch" />
 *       &lt;attribute name="numEntries" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "participantMappingType", propOrder = {
    "mappingEntry"
})
public class ParticipantMappingType {

    @XmlElement(name = "MappingEntry")
    protected List<MappingEntryType> mappingEntry;
    @XmlAttribute(name = "creation-date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(name = "fromExchange", required = true)
    protected String fromExchange;
    @XmlAttribute(name = "toExchange", required = true)
    protected String toExchange;
    @XmlAttribute(name = "numEntries", required = true)
    protected BigInteger numEntries;

    /**
     * Gets the value of the mappingEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mappingEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMappingEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MappingEntryType }
     * 
     * 
     */
    public List<MappingEntryType> getMappingEntry() {
        if (mappingEntry == null) {
            mappingEntry = new ArrayList<MappingEntryType>();
        }
        return this.mappingEntry;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the fromExchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromExchange() {
        if (fromExchange == null) {
            return "RemoteExch";
        } else {
            return fromExchange;
        }
    }

    /**
     * Sets the value of the fromExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromExchange(String value) {
        this.fromExchange = value;
    }

    /**
     * Gets the value of the toExchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToExchange() {
        if (toExchange == null) {
            return "LocalExch";
        } else {
            return toExchange;
        }
    }

    /**
     * Sets the value of the toExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToExchange(String value) {
        this.toExchange = value;
    }

    /**
     * Gets the value of the numEntries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumEntries() {
        return numEntries;
    }

    /**
     * Sets the value of the numEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumEntries(BigInteger value) {
        this.numEntries = value;
    }

}
